name: Deploy to Railway with Docker
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    name: Build and Deploy with Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login a Railway
      - name: Install Railway CLI
        run: npm i -g @railway/cli

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          cd book-reviews-app
          docker build -t book-reviews-app:latest .

      # Desplegar en Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token $RAILWAY_TOKEN
          railway up --service "Project-React-Book-reviews"